services:
  portfolio:
    build:
      context: .
      dockerfile: dockerfile
    image: portfolio-website:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - npm-shared-net


networks:
  npm-shared-net:
    external: true
