# Generated by Django 6.1.2 on 2026-10-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('supporting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_type', models.CharField(choices=[('hero', 'Hero'), ('markdown', 'Markdown'), ('timeline', 'Timeline'), ('card_grid', 'Card grid'), ('skill_groups', 'Skill groups'), ('contact', 'Contact'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_visible', 'order'], name='section_visible_order'), models.Index(fields=['slug'], name='section_slug_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='section_slug_unique')],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('project', 'Project'), ('experience', 'Experience'), ('highlight', 'Highlight'), ('skill', 'Skill'), ('contact_method', 'Contact method')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.section')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='content.sectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_label', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='content.sectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='tag_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='technology_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, max_length=500)),
                ('demo_url', models.URLField(blank=True, max_length=500)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='content.sectionitem')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='content.tag')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='content.technology')),
            ],
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['section', 'is_visible', 'order'], name='item_section_visible_order'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['item_type'], name='item_item_type_idx'),
        ),
    ]
